-- Create enum type "delivery_method"
CREATE TYPE "public"."delivery_method" AS ENUM ('DELIVERY', 'PICKUP', 'SIGNATURE');
-- Create enum type "packaging_type"
CREATE TYPE "public"."packaging_type" AS ENUM ('BOX', 'ENVELOPE', 'BAG', 'CARTON', 'PALLET', 'SHRINK_WRAP');
-- Create enum type "weight_unit"
CREATE TYPE "public"."weight_unit" AS ENUM ('GRAMS', 'KILOGRAMS', 'OUNCES', 'POUNDS');
-- Create enum type "time_unit"
CREATE TYPE "public"."time_unit" AS ENUM ('SECOND', 'MINUTE', 'HOUR');
-- Create enum type "vehicle_consumption_unit"
CREATE TYPE "public"."vehicle_consumption_unit" AS ENUM ('LITERS_PER_100KM', 'KILOMETERS_PER_LITER', 'MILES_PER_GALLON', 'GALLONS_PER_MILE');
-- Create enum type "vehicle_category_type"
CREATE TYPE "public"."vehicle_category_type" AS ENUM ('TRUCK', 'VAN', 'PICKUP', 'MOTORCYCLE', 'BICYCLE');
-- Create enum type "volume_unit"
CREATE TYPE "public"."volume_unit" AS ENUM ('CUBIC_CENTIMETER', 'CUBIC_METER', 'LITER', 'CUBIC_INCH', 'CUBIC_FEET', 'GALLON');
-- Create enum type "vehicle_engine_type"
CREATE TYPE "public"."vehicle_engine_type" AS ENUM ('GASOLINE', 'DIESEL', 'CNG', 'ELECTRIC', 'HYBRID', 'MECHANIC');
-- Create "tenant" table
CREATE TABLE "public"."tenant" ("id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY, "alias" character varying(50) NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "tenant_alias_key" UNIQUE ("alias"));
-- Create enum type "milestone_category"
CREATE TYPE "public"."milestone_category" AS ENUM ('DEPOT', 'DISTRIBUTION_CENTER', 'LOADING_POINT', 'WAREHOUSE', 'TRANSFER_POINT');
-- Create enum type "special_handling"
CREATE TYPE "public"."special_handling" AS ENUM ('FRAGILE', 'PERISHABLE', 'HAZARDOUS', 'REFRIGERATED');
-- Create enum type "delivery_lot_state"
CREATE TYPE "public"."delivery_lot_state" AS ENUM ('UNPROCESSED', 'PROCESSING', 'PROCESSED', 'CANCELED');
-- Create enum type "length_unit"
CREATE TYPE "public"."length_unit" AS ENUM ('CENTIMETER', 'METER', 'KILOMETER', 'INCH', 'FEET', 'MILE');
-- Create "company" table
CREATE TABLE "public"."company" ("id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY, "tenant_id" integer NOT NULL, "alias" character varying(50) NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "fk__company__tenant" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenant" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "company_tenant_id_alias_idx" to table: "company"
CREATE UNIQUE INDEX "company_tenant_id_alias_idx" ON "public"."company" ("tenant_id", "alias");
-- Create "company_user" table
CREATE TABLE "public"."company_user" ("id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY, "company_id" integer NOT NULL, "alias" character varying(50) NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "fk__company_user__company" FOREIGN KEY ("company_id") REFERENCES "public"."company" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "company_user_company_id_alias_idx" to table: "company_user"
CREATE UNIQUE INDEX "company_user_company_id_alias_idx" ON "public"."company_user" ("company_id", "alias");
-- Create "milestone" table
CREATE TABLE "public"."milestone" ("id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY, "company_id" integer NOT NULL, "name" character varying(255) NOT NULL, "location" character varying(25) NOT NULL, "category" "public"."milestone_category" NULL, PRIMARY KEY ("id"), CONSTRAINT "fk__milestone__company" FOREIGN KEY ("company_id") REFERENCES "public"."company" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Set comment to column: "location" on table: "milestone"
COMMENT ON COLUMN "public"."milestone"."location" IS 'ISO 6709:DD (e.g. ''+DD.DDDDDDD+DDD.DDDDDDD/'')';
-- Create "delivery" table
CREATE TABLE "public"."delivery" ("id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY, "company_id" integer NOT NULL, "method" "public"."delivery_method" NULL, "milestone_id" integer NULL, "destination" character varying(25) NULL, "schedules" json NULL, "width" integer NULL, "height" integer NULL, "depth" integer NULL, "length_unit" "public"."length_unit" NULL, "volume" integer NULL, "volume_unit" "public"."volume_unit" NULL, "weight" integer NULL, "weight_unit" "public"."weight_unit" NULL, "packaging" "public"."packaging_type" NULL, "handling" json NULL, "value_cents" integer NULL, "value_currency" character varying(3) NULL, "extra" json NULL, PRIMARY KEY ("id"), CONSTRAINT "fk__delivery__company" FOREIGN KEY ("company_id") REFERENCES "public"."company" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "fk__delivery__milestone" FOREIGN KEY ("milestone_id") REFERENCES "public"."milestone" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Set comment to column: "destination" on table: "delivery"
COMMENT ON COLUMN "public"."delivery"."destination" IS 'ISO 6709:DD (e.g. ''+DD.DDDDDDD+DDD.DDDDDDD/'')';
-- Set comment to column: "schedules" on table: "delivery"
COMMENT ON COLUMN "public"."delivery"."schedules" IS 'List of RFC 5545';
-- Set comment to column: "handling" on table: "delivery"
COMMENT ON COLUMN "public"."delivery"."handling" IS 'List of special handling';
-- Set comment to column: "value_currency" on table: "delivery"
COMMENT ON COLUMN "public"."delivery"."value_currency" IS 'ISO 4217 code';
-- Create "fleet" table
CREATE TABLE "public"."fleet" ("id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY, "company_id" integer NOT NULL, "name" character varying(255) NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "fk__fleet__company" FOREIGN KEY ("company_id") REFERENCES "public"."company" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "delivery_lot" table
CREATE TABLE "public"."delivery_lot" ("id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY, "company_id" integer NOT NULL, "milestone_id" integer NULL, "fleet_id" integer NULL, "state" "public"."delivery_lot_state" NOT NULL DEFAULT 'UNPROCESSED', "vehicle_volume_min" integer NULL, "vehicle_volume_max" integer NULL, "vehicle_capacity_min" integer NULL, "vehicle_capacity_max" integer NULL, "route_stops_min" integer NULL, "route_stops_max" integer NULL, "route_length_min" integer NULL, "route_length_max" integer NULL, "route_length_unit" "public"."length_unit" NULL, "route_time_min" integer NULL, "route_time_max" integer NULL, "route_time_unit" "public"."time_unit" NULL, PRIMARY KEY ("id"), CONSTRAINT "fk__delivery_lot__company" FOREIGN KEY ("company_id") REFERENCES "public"."company" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "fk__delivery_lot__fleet" FOREIGN KEY ("fleet_id") REFERENCES "public"."fleet" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "fk__delivery_lot__milestone" FOREIGN KEY ("milestone_id") REFERENCES "public"."milestone" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Set comment to column: "vehicle_volume_min" on table: "delivery_lot"
COMMENT ON COLUMN "public"."delivery_lot"."vehicle_volume_min" IS 'Minimum loading volume percentage';
-- Set comment to column: "vehicle_volume_max" on table: "delivery_lot"
COMMENT ON COLUMN "public"."delivery_lot"."vehicle_volume_max" IS 'Maximum loading volume percentage';
-- Set comment to column: "vehicle_capacity_min" on table: "delivery_lot"
COMMENT ON COLUMN "public"."delivery_lot"."vehicle_capacity_min" IS 'Minimum packages capacity';
-- Set comment to column: "vehicle_capacity_max" on table: "delivery_lot"
COMMENT ON COLUMN "public"."delivery_lot"."vehicle_capacity_max" IS 'Maximum packages capacity';
-- Set comment to column: "route_stops_min" on table: "delivery_lot"
COMMENT ON COLUMN "public"."delivery_lot"."route_stops_min" IS 'Minimum required stops';
-- Set comment to column: "route_stops_max" on table: "delivery_lot"
COMMENT ON COLUMN "public"."delivery_lot"."route_stops_max" IS 'Maximum required stops';
-- Set comment to column: "route_length_min" on table: "delivery_lot"
COMMENT ON COLUMN "public"."delivery_lot"."route_length_min" IS 'Minimum distance for a delivery route';
-- Set comment to column: "route_length_max" on table: "delivery_lot"
COMMENT ON COLUMN "public"."delivery_lot"."route_length_max" IS 'Maximum distance for a delivery route';
-- Set comment to column: "route_time_min" on table: "delivery_lot"
COMMENT ON COLUMN "public"."delivery_lot"."route_time_min" IS 'Minimum delivery route time';
-- Set comment to column: "route_time_max" on table: "delivery_lot"
COMMENT ON COLUMN "public"."delivery_lot"."route_time_max" IS 'Maximum delivery route time';
-- Create "delivery_lot_delivery" table
CREATE TABLE "public"."delivery_lot_delivery" ("delivery_lot_id" integer NOT NULL, "delivery_id" integer NOT NULL, PRIMARY KEY ("delivery_lot_id", "delivery_id"), CONSTRAINT "fk__delivery_lot_delivery__delivery" FOREIGN KEY ("delivery_id") REFERENCES "public"."delivery" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "fk__delivery_lot_delivery__delivery_lot" FOREIGN KEY ("delivery_lot_id") REFERENCES "public"."delivery_lot" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "driver" table
CREATE TABLE "public"."driver" ("id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY, "company_id" integer NOT NULL, "first_name" character varying(50) NOT NULL, "last_name" character varying(50) NULL, "work_schedules" json NULL, "start_point" character varying(25) NULL, "end_point" character varying(25) NULL, "work_areas" json NULL, PRIMARY KEY ("id"), CONSTRAINT "fk__driver__company" FOREIGN KEY ("company_id") REFERENCES "public"."company" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Set comment to column: "work_schedules" on table: "driver"
COMMENT ON COLUMN "public"."driver"."work_schedules" IS 'List of RFC 5545';
-- Set comment to column: "start_point" on table: "driver"
COMMENT ON COLUMN "public"."driver"."start_point" IS 'ISO 6709:DD (e.g. ''+DD.DDDDDDD+DDD.DDDDDDD/'')';
-- Set comment to column: "end_point" on table: "driver"
COMMENT ON COLUMN "public"."driver"."end_point" IS 'ISO 6709:DD (e.g. ''+DD.DDDDDDD+DDD.DDDDDDD/'')';
-- Set comment to column: "work_areas" on table: "driver"
COMMENT ON COLUMN "public"."driver"."work_areas" IS 'List of lists of geographic working areas (ISO 6709:DD)';
-- Create "delivery_lot_driver" table
CREATE TABLE "public"."delivery_lot_driver" ("delivery_lot_id" integer NOT NULL, "driver_id" integer NOT NULL, PRIMARY KEY ("delivery_lot_id", "driver_id"), CONSTRAINT "fk__delivery_lot_driver__delivery_lot" FOREIGN KEY ("delivery_lot_id") REFERENCES "public"."delivery_lot" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "fk__delivery_lot_driver__driver" FOREIGN KEY ("driver_id") REFERENCES "public"."driver" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "delivery_plan" table
CREATE TABLE "public"."delivery_plan" ("id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY, "delivery_lot_id" integer NOT NULL, "optimizer_id" character varying(36) NULL, PRIMARY KEY ("id"), CONSTRAINT "fk__delivery_plan__delivery_lot" FOREIGN KEY ("delivery_lot_id") REFERENCES "public"."delivery_lot" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Set comment to column: "optimizer_id" on table: "delivery_plan"
COMMENT ON COLUMN "public"."delivery_plan"."optimizer_id" IS 'UUID';
-- Create "vehicle" table
CREATE TABLE "public"."vehicle" ("id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY, "company_id" integer NOT NULL, "name" character varying(255) NOT NULL, "volume" integer NULL, "volume_unit" "public"."volume_unit" NULL, "consumption" integer NULL, "consumption_unit" "public"."vehicle_consumption_unit" NULL, "category_type" "public"."vehicle_category_type" NULL, "engine_type" "public"."vehicle_engine_type" NULL, PRIMARY KEY ("id"), CONSTRAINT "fk__vehicle__company" FOREIGN KEY ("company_id") REFERENCES "public"."company" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "delivery_path" table
CREATE TABLE "public"."delivery_path" ("id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY, "delivery_plan_id" integer NOT NULL, "milestone_id" integer NOT NULL, "vehicle_id" integer NULL, "driver_id" integer NULL, PRIMARY KEY ("id"), CONSTRAINT "fk__delivery_path__delivery_plan" FOREIGN KEY ("delivery_plan_id") REFERENCES "public"."delivery_plan" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "fk__delivery_path__driver" FOREIGN KEY ("driver_id") REFERENCES "public"."driver" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "fk__delivery_path__milestone" FOREIGN KEY ("milestone_id") REFERENCES "public"."milestone" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "fk__delivery_path__vehicle" FOREIGN KEY ("vehicle_id") REFERENCES "public"."vehicle" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create "delivery_path_delivery" table
CREATE TABLE "public"."delivery_path_delivery" ("delivery_path_id" integer NOT NULL, "delivery_id" integer NOT NULL, "delivery_order" integer NOT NULL, PRIMARY KEY ("delivery_path_id", "delivery_id"), CONSTRAINT "fk__delivery_path_delivery__delivery" FOREIGN KEY ("delivery_id") REFERENCES "public"."delivery" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "fk__delivery_path_delivery__delivery_path" FOREIGN KEY ("delivery_path_id") REFERENCES "public"."delivery_path" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "delivery_path_delivery_delivery_path_id_delivery_order_idx" to table: "delivery_path_delivery"
CREATE UNIQUE INDEX "delivery_path_delivery_delivery_path_id_delivery_order_idx" ON "public"."delivery_path_delivery" ("delivery_path_id", "delivery_order");
-- Create "driver_vehicle" table
CREATE TABLE "public"."driver_vehicle" ("driver_id" integer NOT NULL, "vehicle_id" integer NOT NULL, "quantity" integer NOT NULL, PRIMARY KEY ("driver_id", "vehicle_id"), CONSTRAINT "fk__driver_vehicle__driver" FOREIGN KEY ("driver_id") REFERENCES "public"."driver" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "fk__driver_vehicle__vehicle" FOREIGN KEY ("vehicle_id") REFERENCES "public"."vehicle" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "fleet_vehicle" table
CREATE TABLE "public"."fleet_vehicle" ("fleet_id" integer NOT NULL, "vehicle_id" integer NOT NULL, "quantity" integer NOT NULL, PRIMARY KEY ("fleet_id", "vehicle_id"), CONSTRAINT "fk__fleet_vehicle__fleet" FOREIGN KEY ("fleet_id") REFERENCES "public"."fleet" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "fk__fleet_vehicle__vehicle" FOREIGN KEY ("vehicle_id") REFERENCES "public"."vehicle" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "tenant_user" table
CREATE TABLE "public"."tenant_user" ("id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY, "tenant_id" integer NOT NULL, "alias" character varying(50) NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "fk__tenant_user__company" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenant" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "tenant_user_tenant_id_alias_idx" to table: "tenant_user"
CREATE UNIQUE INDEX "tenant_user_tenant_id_alias_idx" ON "public"."tenant_user" ("tenant_id", "alias");
